spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/ph_old?serverTimezone=Asia/Shanghai&useSSL=false&zeroDateTimeBehavior=convertToNull
  rabbitmq:
    host: 192.168.10.100
    port: 5673
    username: guest
    password: guest
    virtual-host: /