spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: zuo
    password: 1234
    url: jdbc:mysql://47.97.208.219:3306/ph_old?serverTimezone=Asia/Shanghai&useSSL=false
server:
  port: 8087
